language: r
sudo: false
cache: packages

r:
  - release

r_packages:
  - rgenoud

r_github_packages:
  - berndbischl/ParamHelpers
  - mlr-org/mlr
  - mlr-org/mlrMBO
  - jimhester/covr

warnings_are_errors: true

after_success:
   - Rscript -e 'covr::coveralls()'